[package]
name = "openehr"
version = "0.1.0"
edition = "2021"

[lib]
name = "openehr"
path = "src/lib.rs"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
thiserror = "1.0"
uuid = { version = "1" }
